ADONetMovie_RazorPages/Pages/Movies/GetMovies.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ADONetMovie_RazorPages.Models;
using ADONetMovie_RazorPages.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ADONetMovie_RazorPages.Pages.Movies
{
    public class GetMoviesModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string FilterCriteria { get; set; }
        public IEnumerable<Movie> Movies { get; set; }

        IMovieService movieService { get; set; }
        public GetMoviesModel(IMovieService service)
        {
            movieService = service;
         }
        public void OnGet()
        {
           Movies = movieService.GetMovies();
        }

        public void OnGetMoviesByActor(int aid)
        {
           Movies = movieService.GetMoviesByActor(aid);
        }

        public void OnGetMoviesByStudio(int sid)
        {
            Movies = movieService.GetMoviesByStudio(sid);
        }
        public void OnPost()
        {

        }
    }
}

ADONetMovie_RazorPages/Pages/Movies/StudiosActorsByMovie.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ADONetMovie_RazorPages.Models;
using ADONetMovie_RazorPages.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ADONetMovie_RazorPages.Pages.Movies
{
    public class StudiosActorsByMovieModel : PageModel
    {
        IMovieService movieService;
        IActorService actorService;
        IStudioService studioService;

        public Movie Movie { get; set; }
        public Actor Actor { get; set; }
        public Studio Studio { get; set; }
        public StudiosActorsByMovieModel(IMovieService mservice, IActorService aservice,  IStudioService sservice)
        {
            movieService = mservice;
            actorService = aservice;
            studioService = sservice;
        }
        public void OnGetStudiosActorsPerMovie(int mid,  int sid, int aid)
        {
            Movie = movieService.GetMovieById(mid);
            Actor = actorService.GetActorById(aid);
            Studio = studioService.GetStudioById(sid);
            
        }
    }
}

ADONetMovie_RazorPages/Pages/Movies/GetMovies.cshtml
@page
@model ADONetMovie_RazorPages.Pages.Movies.GetMoviesModel
@{
    ViewData["Title"] = "GetMovies";
}
<h1>List of movies</h1>
<p>
    <a asp-page="/Movies/Create">Create New Movie</a>
</p>
<form>
    <p>
        Search: <input type="text" asp-for="FilterCriteria" />
        <input type="submit" value="Filter" />
        <a asp-page="/Movies/GetMovies">Back to Full List </a>
    </p>
</form>
<h4 style="color:red"> List of movies</h4>
<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Title
            </th>
            <th>
                Year
            </th>
            <th>
                Country
            </th>
            <th>
                Studio Id
            </th>
            <th>
                Actor Id
            </th>
        </tr>
    </thead>
    <tbody>

        @if (Model.Movies != null)
        {
            @foreach (var item in Model.Movies)
            {
        <tr>
            <td>
                @item.Id
            </td>
            <td>
                @item.Title
            </td>
            <td>
                @item.Year
            </td>
            <td>
                @item.RunningTimeInMins
            </td>
            <td>
                @item.StudioId
            </td>
            <td>
                @item.ActorId
            </td>
            <td>
                <p>
                    <a asp-page="/Movies/StudiosActorsByMovie" asp-page-handler="StudiosActorsPerMovie"  asp-route-mid="@item.Id" asp-route-sid="@item.StudioId"    asp-route-aid="@item.ActorId"  > Studios && Actors  </a>
                </p>
            </td>
        </tr>
            }
        }
</table>

ADONetMovie_RazorPages/Pages/Movies/StudiosActorsByMovie.cshtml
@page
@model ADONetMovie_RazorPages.Pages.Movies.StudiosActorsByMovieModel
@{
}
<table class="table">
    <thead>
        <tr>
            <th>  Movie  Title   </th>
            <th> Actor Name   </th>
            <th> From   </th>
            <th>  Studio Name   </th>
            <th>  Studio HQCity   </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>   @Model.Movie.Title    </td>
            <td>   @Model.Actor.Name   </td>
            <td>   @Model.Actor.Country   </td>
            <td>  @Model.Studio.Name  </td>
            <td>  @Model.Studio.Hqcity </td>

        </tr>
</table>