ADONetMovie_RazorPages/Models/Studio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace ADONetMovie_RazorPages.Models
{
    [Table("Studio")]
    public partial class Studio
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [Column("HQCity")]
        [StringLength(30)]
        public string Hqcity { get; set; }
        public int NoOfEmployees { get; set; }
    }
}

ADONetMovie_RazorPages/Pages/Movies/GetMovies.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ADONetMovie_RazorPages.Models;
using ADONetMovie_RazorPages.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ADONetMovie_RazorPages.Pages.Movies
{
    public class GetMoviesModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string FilterCriteria { get; set; }
        public IEnumerable<Movie> Movies { get; set; }

        IMovieService movieService { get; set; }
        public GetMoviesModel(IMovieService service)
        {
            movieService = service;
         }
        public void OnGet()
        {
           Movies = movieService.GetMovies();
        }

        public void OnGetMoviesByActor(int aid)
        {
           Movies = movieService.GetMoviesByActor(aid);
        }

        public void OnGetMoviesByStudio(int sid)
        {
            Movies = movieService.GetMoviesByStudio(sid);
        }
        public void OnPost()
        {

        }
    }
}

ADONetMovie_RazorPages/Pages/Studios/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ADONetMovie_RazorPages.Models;
using ADONetMovie_RazorPages.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ADONetMovie_RazorPages
{
    public class CreateModel : PageModel
    {
        [BindProperty]
        public Studio Studio { get; set; }
        public void OnGet()
        {
         }
        IStudioService studioService;
        public CreateModel(IStudioService service)
        {
            this.studioService = service;
        }
        public IActionResult OnPostAsync(Studio studio)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            studioService.AddStudio(studio);
            return RedirectToPage("GetStudios");
        }
    }
}

ADONetMovie_RazorPages/Pages/Studios/GetStudios.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ADONetMovie_RazorPages.Models;
using ADONetMovie_RazorPages.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ADONetMovie_RazorPages.Pages.Studios
{
    public class GetStudiosModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public Studio Studio { get; set; }

        private IStudioService studioService;

        public GetStudiosModel(IStudioService service)
        {
            studioService = service;
        }      
        public IEnumerable<Studio> Studios { get; set; } = new List<Studio>();
        public void OnGet()
        {
            if (!String.IsNullOrEmpty(Studio.Hqcity) || !String.IsNullOrEmpty(Studio.Name))
            {
                Studios = studioService.GetStudios(Studio.Hqcity, Studio.Name);
            }
            else
                Studios = studioService.GetStudios();
        }
        public void OnPost()
        {

        }
    }
}

ADONetMovie_RazorPages/Pages/Studios/Create.cshtml
@page
@model ADONetMovie_RazorPages.CreateModel
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="  ModelOnly  " class="text-danger">
            </div>

            <div class="form-group">
                <label asp-for="@Model.Studio.Id" class="control-label"></label>
                <input asp-for="@Model.Studio.Id" class="form-control" />
                <span asp-validation-for="@Model.Studio.Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Studio.Name" class="control-label"></label>
                <input asp-for="@Model.Studio.Name" class="form-control" />
                <span asp-validation-for="@Model.Studio.Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.Studio.NoOfEmployees" class="control-label"></label>
                <input asp-for="@Model.Studio.NoOfEmployees" class="form-control" />
                <span asp-validation-for="@Model.Studio.NoOfEmployees" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Studio.Hqcity" class="control-label"></label>
                <input asp-for="@Model.Studio.Hqcity" class="form-control" />
                <span asp-validation-for="@Model.Studio.Hqcity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

ADONetMovie_RazorPages/Pages/Studios/GetStudios.cshtml
@page
@model  ADONetMovie_RazorPages.Pages.Studios.GetStudiosModel
@{
    ViewData["Title"] = "GetStudios";
}

<h1>List of studios</h1>
<p>
    <a asp-page="/Studios/Create">Create New Studio</a>
</p>
<form>
    <p>
        HQCity: <input type="text" asp-for="@Model.Studio.Hqcity" />
        Name: <input type="text" asp-for="@Model.Studio.Name" />
        <input type="submit" value="Filter" />
        <a asp-page="/Studios/GetStudios">Back to Full List </a>
    </p>
</form>
<h4 style="color:red"> List of studios</h4>
<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Name
            </th>
            <th>
                Hqcity
            </th>

            <th>
                Number of employee
            </th>
        </tr>
    </thead>
    <tbody>

        @if (Model != null)
        {
            @foreach (var item in Model.Studios)
            {
        <tr>
            <td>
                @item.Id
            </td>
            <td>
                @item.Name
            </td>
            <td>
                @item.Hqcity
            </td>
            <td>
                @item.NoOfEmployees
            </td>
            <td>
                <p>
                    <a asp-page="/Movies/GetMovies" asp-page-handler="MoviesByStudio" asp-route-sid="@item.Id"> Studio´s movies  </a>
                </p>
            </td>
        </tr>
            }
        }
</table>