ADONetMovie_RazorPages/Models/Actor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ADONetMovie_RazorPages.Models
{
    public class Actor
    {
        public int Id { get; set;}
        public string Name { get; set; }
        public string Country { get; set; }
        public DateTime Birth_year { get; set; }
        public bool Alive { get; set; }
    }
}

ADONetMovie_RazorPages/Pages/Actors/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ADONetMovie_RazorPages.Models;
using ADONetMovie_RazorPages.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ADONetMovie_RazorPages.Pages.Actors
{
    public class DeleteModel : PageModel
    {
        IActorService actorService;
       public DeleteModel(IActorService service)
        {
            this.actorService = service;
           
        }
        [BindProperty]
        public Actor Actor { get; set; }

        public IActionResult OnGet(int id)
        {
            Actor = actorService.GetActorById(id);
            return Page();
        }
        public IActionResult OnPostAsync()
        {
            actorService.DeleteActor(Actor);
            return RedirectToPage("GetActors");
        }
    }
}

ADONetMovie_RazorPages/Pages/Actors/GetActors.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ADONetMovie_RazorPages.Models;
using ADONetMovie_RazorPages.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ADONetMovie_RazorPages
{
    public class GetActorsModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string FilterCriteria { get; set; }
        public IEnumerable<Actor> Actors{ get; set; }

        IActorService actorService { get; set; }
        public GetActorsModel(IActorService service)
        {
            actorService = service;
        }
        public void OnGet()
        {
            //if (!String.IsNullOrEmpty(FilterCriteria))
            //{
            //    Movies = movieService.GetMovies(FilterCriteria);
            //}
            //else
            Actors = actorService.GetActors();
        }

        public void OnGetMovies(int aid)
        {

        }
        public void OnPost()
        {

        }
    }
}

ADONetMovie_RazorPages/Pages/Movies/GetMovies.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ADONetMovie_RazorPages.Models;
using ADONetMovie_RazorPages.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ADONetMovie_RazorPages.Pages.Movies
{
    public class GetMoviesModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string FilterCriteria { get; set; }
        public IEnumerable<Movie> Movies { get; set; }

        IMovieService movieService { get; set; }
        public GetMoviesModel(IMovieService service)
        {
            movieService = service;
         }
        public void OnGet()
        {
           Movies = movieService.GetMovies();
        }

        public void OnGetMoviesByActor(int aid)
        {
           Movies = movieService.GetMoviesByActor(aid);
        }

        public void OnGetMoviesByStudio(int sid)
        {
            Movies = movieService.GetMoviesByStudio(sid);
        }
        public void OnPost()
        {

        }
    }
}

ADONetMovie_RazorPages/Pages/Actors/Delete.cshtml
@page
@model ADONetMovie_RazorPages.Pages.Actors.DeleteModel
@{
}
<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Actor.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Actor.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Actor.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Actor.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Actor.Birth_year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Actor.Birth_year)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Actor.Country)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Actor.Country)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Actor.Country)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Actor.Country)
        </dd>
    </dl>

    <form method="post">
        <input type="hidden" asp-for="Actor.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

ADONetMovie_RazorPages/Pages/Actors/GetActors.cshtml
@page
@model ADONetMovie_RazorPages.GetActorsModel
@{
    ViewData["Title"] = "GetActors";
}

<p>
    <a asp-page="/Movies/Create">Create New Actor</a>
</p>
<form>
    <p>
        Search: <input type="text" asp-for="FilterCriteria" />
        <input type="submit" value="Filter" />
        <a asp-page="/Movies/GetMovies">Back to Full List </a>
    </p>
</form>
<h4 style="color:red"> List of actors</h4>
<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Name
            </th>
            <th>
                Birth Year
            </th>
            <th>
                Alive
            </th>
            <th>
                Country
            </th>
        </tr>
    </thead>
    <tbody>

        @if (Model.Actors != null)

            @foreach (var item in Model.Actors)
            {
        <tr>
            <td>
                @item.Id
            </td>
            <td>
                @item.Name
            </td>
            <td>
                @item.Birth_year
            </td>

            <td>
                @item.Alive
            </td>
            <td>
                @item.Country
            </td>
            <td>
                <p>
                    <a asp-page="/Movies/GetMovies" asp-page-handler="MoviesByActor" asp-route-aid="@item.Id"> Actor´s movies  </a>
                </p>
            </td> 
            <td>
                <p> <a asp-page="/Actors/Delete" asp-route-id="@item.Id">Delete Actor</a> </p>
            </td>
        </tr>
                }
    </table>